server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/authforge}
    username: ${DB_USERNAME:authforge}
    password: ${DB_PASSWORD:authforge}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    default-property-inclusion: non_null

authforge:
  jwt:
    secret: ${JWT_SECRET:my-super-secret-key-that-should-be-at-least-256-bits-long-for-hs256}
    access-token-expiration: 900000
    refresh-token-expiration: 604800000
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5500}

logging:
  level:
    com.authforge: DEBUG
    org.springframework.security: INFO
